name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: thursdayreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t thursdayreg.azurecr.io/k8sdemo:${{ github.sha }}
        docker push thursdayreg.azurecr.io/k8sdemo:${{ github.sha }}

  deploy:
  
      runs-on: ubuntu-latest
      needs: build
  
      steps:
      - uses: azure/docker-login@v1
        with:
          login-server: thursdayreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'newappthur'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: 'thursdayreg.azurecr.io/k8sdemo:${{ github.sha }}'
          
